# Generated by Django 4.2.7 on 2023-12-07 13:13

from django.db import migrations, models
import django.utils.timezone
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 day')),
                ('device_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=50, verbose_name='Status')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Battery Level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
